version: "3"

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/books
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A task worker -l info
    volumes:
      - .:/books
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_USER=tasks
      - POSTGRES_PASSWORD=tasks
    depends_on:
      - db
      - redis
      - web
